package FormularioUsuario;

/**
 *
 * @author ITCODE
 */
public class FormularioUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioUsuario
     */
    public FormularioUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPpanelRegistroUsuario = new javax.swing.JPanel();
        RHBpanelbotones = new javax.swing.JPanel();
        RHBregistrar = new javax.swing.JButton();
        RHBregresar = new javax.swing.JButton();
        RHBactualizar = new javax.swing.JButton();
        RHBeliminar = new javax.swing.JButton();
        RHpanelregistroUsuario = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        TXTnombreusuario = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        TXTidempleado = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        TXTapellidousuario = new javax.swing.JTextField();
        TXTcontraseña = new javax.swing.JTextField();
        TXTusuario = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        RHCBOarea = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        TXTbuscarusuario = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        TXTrepitircontraseña = new javax.swing.JTextField();
        RHbuscar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        RHBpanelbotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOTONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        RHBpanelbotones.setForeground(new java.awt.Color(0, 255, 51));

        RHBregistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RHBregistrar.setForeground(new java.awt.Color(0, 255, 51));
        RHBregistrar.setText("Registrar");

        RHBregresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RHBregresar.setForeground(new java.awt.Color(0, 255, 51));
        RHBregresar.setText("Regresar");
        RHBregresar.setToolTipText("");

        RHBactualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RHBactualizar.setForeground(new java.awt.Color(0, 255, 51));
        RHBactualizar.setText("Actualizar");

        RHBeliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RHBeliminar.setForeground(new java.awt.Color(0, 255, 51));
        RHBeliminar.setText("Eliminar");
        RHBeliminar.setToolTipText("");

        javax.swing.GroupLayout RHBpanelbotonesLayout = new javax.swing.GroupLayout(RHBpanelbotones);
        RHBpanelbotones.setLayout(RHBpanelbotonesLayout);
        RHBpanelbotonesLayout.setHorizontalGroup(
            RHBpanelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHBpanelbotonesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(RHBpanelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RHBregresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RHBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RHBactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(RHBregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        RHBpanelbotonesLayout.setVerticalGroup(
            RHBpanelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHBpanelbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RHBregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RHBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RHBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RHBregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        RHpanelregistroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 51))); // NOI18N
        RHpanelregistroUsuario.setForeground(new java.awt.Color(0, 255, 51));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 255, 51));
        jLabel40.setText("ID:");

        TXTnombreusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTnombreusuario.setForeground(new java.awt.Color(0, 255, 51));
        TXTnombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreusuarioActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 255, 51));
        jLabel41.setText("Nombre:");

        TXTidempleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTidempleado.setForeground(new java.awt.Color(0, 255, 51));
        TXTidempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidempleadoActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 255, 51));
        jLabel42.setText("Repitir Contraseña:");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 255, 51));
        jLabel43.setText("Apellidos:");

        TXTapellidousuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTapellidousuario.setForeground(new java.awt.Color(0, 255, 51));
        TXTapellidousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTapellidousuarioActionPerformed(evt);
            }
        });

        TXTcontraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTcontraseña.setForeground(new java.awt.Color(0, 255, 51));
        TXTcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcontraseñaActionPerformed(evt);
            }
        });

        TXTusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTusuario.setForeground(new java.awt.Color(0, 255, 51));
        TXTusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTusuarioActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 255, 51));
        jLabel48.setText("Usuario:");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 255, 51));
        jLabel49.setText("Area");

        RHCBOarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RHCBOarea.setForeground(new java.awt.Color(0, 255, 51));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 255, 51));
        jLabel52.setText("Buscador ID/Usuario:");

        TXTbuscarusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTbuscarusuario.setForeground(new java.awt.Color(0, 255, 51));
        TXTbuscarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTbuscarusuarioActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 255, 51));
        jLabel45.setText("Contraseña:");

        TXTrepitircontraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTrepitircontraseña.setForeground(new java.awt.Color(0, 255, 51));
        TXTrepitircontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTrepitircontraseñaActionPerformed(evt);
            }
        });

        RHbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RHbuscar.setForeground(new java.awt.Color(0, 255, 51));
        RHbuscar.setText("Buscar");

        javax.swing.GroupLayout RHpanelregistroUsuarioLayout = new javax.swing.GroupLayout(RHpanelregistroUsuario);
        RHpanelregistroUsuario.setLayout(RHpanelregistroUsuarioLayout);
        RHpanelregistroUsuarioLayout.setHorizontalGroup(
            RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                        .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel52)
                            .addComponent(jLabel41)
                            .addComponent(jLabel43)
                            .addComponent(jLabel40))
                        .addGap(18, 18, 18)
                        .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTapellidousuario)
                            .addComponent(TXTnombreusuario)
                            .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                                        .addComponent(TXTbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RHbuscar)))
                                .addGap(0, 4, Short.MAX_VALUE))))
                    .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                        .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(RHCBOarea, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel48)
                                .addGap(18, 18, 18)
                                .addComponent(TXTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTcontraseña))
                    .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTrepitircontraseña)))
                .addContainerGap())
        );
        RHpanelregistroUsuarioLayout.setVerticalGroup(
            RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RHpanelregistroUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RHbuscar))
                .addGap(16, 16, 16)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTapellidousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTrepitircontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RHpanelregistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RHCBOarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout JPpanelRegistroUsuarioLayout = new javax.swing.GroupLayout(JPpanelRegistroUsuario);
        JPpanelRegistroUsuario.setLayout(JPpanelRegistroUsuarioLayout);
        JPpanelRegistroUsuarioLayout.setHorizontalGroup(
            JPpanelRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPpanelRegistroUsuarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(RHpanelregistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(RHBpanelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        JPpanelRegistroUsuarioLayout.setVerticalGroup(
            JPpanelRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPpanelRegistroUsuarioLayout.createSequentialGroup()
                .addComponent(RHpanelregistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPpanelRegistroUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RHBpanelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPpanelRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPpanelRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreusuarioActionPerformed

    private void TXTidempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidempleadoActionPerformed

    private void TXTapellidousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTapellidousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTapellidousuarioActionPerformed

    private void TXTcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcontraseñaActionPerformed

    private void TXTusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTusuarioActionPerformed

    private void TXTbuscarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTbuscarusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTbuscarusuarioActionPerformed

    private void TXTrepitircontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTrepitircontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTrepitircontraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPpanelRegistroUsuario;
    private javax.swing.JButton RHBactualizar;
    private javax.swing.JButton RHBeliminar;
    private javax.swing.JPanel RHBpanelbotones;
    private javax.swing.JButton RHBregistrar;
    private javax.swing.JButton RHBregresar;
    private javax.swing.JComboBox<String> RHCBOarea;
    private javax.swing.JButton RHbuscar;
    private javax.swing.JPanel RHpanelregistroUsuario;
    private javax.swing.JTextField TXTapellidousuario;
    private javax.swing.JTextField TXTbuscarusuario;
    private javax.swing.JTextField TXTcontraseña;
    private javax.swing.JTextField TXTidempleado;
    private javax.swing.JTextField TXTnombreusuario;
    private javax.swing.JTextField TXTrepitircontraseña;
    private javax.swing.JTextField TXTusuario;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    // End of variables declaration//GEN-END:variables
}
