/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FormularioPrincipal;

/**
 *
 * @author ITCODE
 */
public class FormularioPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        JPprincipal = new javax.swing.JPanel();
        BTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JPmenu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        RHusuarioPrincipal = new javax.swing.JMenu();
        RHpersonalPrincipal = new javax.swing.JMenu();
        RHjornadaPrincipal = new javax.swing.JMenu();
        RHpagosPrincipal = new javax.swing.JMenu();
        RHadelantosPrincipal = new javax.swing.JMenu();
        RHextrasPrincipal = new javax.swing.JMenu();
        RHvacacionesPrinicipal = new javax.swing.JMenu();
        RHasistenciaPrinicpal = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu81 = new javax.swing.JMenu();
        RHreportesPrincipal = new javax.swing.JMenu();
        RHvolverPrinicpal = new javax.swing.JMenu();
        jMenu82 = new javax.swing.JMenu();
        jMenu89 = new javax.swing.JMenu();
        jMenu84 = new javax.swing.JMenu();
        jMenu85 = new javax.swing.JMenu();
        jMenu86 = new javax.swing.JMenu();
        jMenu87 = new javax.swing.JMenu();
        jMenu88 = new javax.swing.JMenu();
        jMenu90 = new javax.swing.JMenu();
        jMenu91 = new javax.swing.JMenu();
        jMenu92 = new javax.swing.JMenu();
        jMenu93 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenu55 = new javax.swing.JMenu();
        jMenu83 = new javax.swing.JMenu();
        jMenu56 = new javax.swing.JMenu();
        jMenu57 = new javax.swing.JMenu();
        jMenu58 = new javax.swing.JMenu();
        jMenu59 = new javax.swing.JMenu();
        jMenu60 = new javax.swing.JMenu();
        jMenu61 = new javax.swing.JMenu();
        jMenu62 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu63 = new javax.swing.JMenu();
        jMenu64 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu65 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu66 = new javax.swing.JMenu();
        jMenu67 = new javax.swing.JMenu();
        jMenu68 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu69 = new javax.swing.JMenu();
        jMenu70 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu71 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu72 = new javax.swing.JMenu();
        jMenu73 = new javax.swing.JMenu();
        jMenu74 = new javax.swing.JMenu();
        jMenu75 = new javax.swing.JMenu();
        jMenu76 = new javax.swing.JMenu();
        jMenu77 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu80 = new javax.swing.JMenu();
        jMenu94 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        BTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN.setForeground(new java.awt.Color(0, 255, 51));
        BTN.setText("Almacen");
        BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 51));
        jButton1.setText("Recursos humanos");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 51));
        jButton3.setText("COMPRAS");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 255, 51));
        jButton4.setText("VENTAS");

        javax.swing.GroupLayout JPprincipalLayout = new javax.swing.GroupLayout(JPprincipal);
        JPprincipal.setLayout(JPprincipalLayout);
        JPprincipalLayout.setHorizontalGroup(
            JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPprincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(679, Short.MAX_VALUE))
        );
        JPprincipalLayout.setVerticalGroup(
            JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPprincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(444, Short.MAX_VALUE))
        );

        jMenu3.setText("Recursos Humanos");

        RHusuarioPrincipal.setText("Usuarios");
        RHusuarioPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RHusuarioPrincipalActionPerformed(evt);
            }
        });
        jMenu3.add(RHusuarioPrincipal);

        RHpersonalPrincipal.setText("Personal");
        jMenu3.add(RHpersonalPrincipal);

        RHjornadaPrincipal.setText("Jornada");
        jMenu3.add(RHjornadaPrincipal);

        RHpagosPrincipal.setText("Pagos");
        jMenu3.add(RHpagosPrincipal);

        RHadelantosPrincipal.setText("Adelantos");
        jMenu3.add(RHadelantosPrincipal);

        RHextrasPrincipal.setText("Extras");
        jMenu3.add(RHextrasPrincipal);

        RHvacacionesPrinicipal.setText("vacaciones");
        jMenu3.add(RHvacacionesPrinicipal);

        RHasistenciaPrinicpal.setForeground(new java.awt.Color(0, 255, 51));
        RHasistenciaPrinicpal.setText("Registro Asistencia");

        jMenu19.setForeground(new java.awt.Color(0, 255, 51));
        jMenu19.setText("Control Personal");

        jMenu27.setForeground(new java.awt.Color(0, 255, 51));
        jMenu27.setText("Registro de Asistencia");
        jMenu19.add(jMenu27);

        RHasistenciaPrinicpal.add(jMenu19);

        jMenu20.setForeground(new java.awt.Color(0, 255, 51));
        jMenu20.setText("Control");

        jMenu28.setForeground(new java.awt.Color(0, 255, 51));
        jMenu28.setText("Gestion de Horrario");
        jMenu20.add(jMenu28);

        jMenu29.setForeground(new java.awt.Color(0, 255, 51));
        jMenu29.setText("Tabla de descuento por Tardanza ");
        jMenu20.add(jMenu29);

        RHasistenciaPrinicpal.add(jMenu20);

        jMenu21.setForeground(new java.awt.Color(0, 255, 51));
        jMenu21.setText("Reporte");

        jMenu30.setForeground(new java.awt.Color(0, 255, 51));
        jMenu30.setText("Buscador");
        jMenu21.add(jMenu30);

        RHasistenciaPrinicpal.add(jMenu21);

        jMenu22.setForeground(new java.awt.Color(0, 255, 51));
        jMenu22.setText("Tiempo extra");

        jMenu31.setForeground(new java.awt.Color(0, 255, 51));
        jMenu31.setText("Horas extras");
        jMenu22.add(jMenu31);

        jMenu32.setForeground(new java.awt.Color(0, 255, 51));
        jMenu32.setText("Control Horas");
        jMenu22.add(jMenu32);

        RHasistenciaPrinicpal.add(jMenu22);

        jMenu23.setForeground(new java.awt.Color(0, 255, 51));
        jMenu23.setText("Tipo de asistencia");

        jMenu33.setForeground(new java.awt.Color(0, 255, 51));
        jMenu33.setText("Asistio");
        jMenu23.add(jMenu33);

        jMenu34.setForeground(new java.awt.Color(0, 255, 51));
        jMenu34.setText("Faltas");
        jMenu23.add(jMenu34);

        jMenu35.setForeground(new java.awt.Color(0, 255, 51));
        jMenu35.setText("Tardanza");
        jMenu23.add(jMenu35);

        jMenu36.setForeground(new java.awt.Color(0, 255, 51));
        jMenu36.setText("Faltas Injustificadas");
        jMenu23.add(jMenu36);

        jMenu37.setForeground(new java.awt.Color(0, 255, 51));
        jMenu37.setText("Faltas justificadas");
        jMenu23.add(jMenu37);

        RHasistenciaPrinicpal.add(jMenu23);

        jMenu24.setForeground(new java.awt.Color(0, 255, 51));
        jMenu24.setText("Entra/Salida");
        RHasistenciaPrinicpal.add(jMenu24);

        jMenu25.setForeground(new java.awt.Color(0, 255, 51));
        jMenu25.setText("Imprimir");
        RHasistenciaPrinicpal.add(jMenu25);

        jMenu26.setForeground(new java.awt.Color(0, 255, 51));
        jMenu26.setText("Licencia");
        RHasistenciaPrinicpal.add(jMenu26);

        jMenu81.setForeground(new java.awt.Color(0, 255, 51));
        jMenu81.setText("Salir");
        RHasistenciaPrinicpal.add(jMenu81);

        jMenu3.add(RHasistenciaPrinicpal);

        RHreportesPrincipal.setText("Reportes");
        jMenu3.add(RHreportesPrincipal);

        RHvolverPrinicpal.setText("Volver");
        jMenu3.add(RHvolverPrinicpal);

        JPmenu.add(jMenu3);

        jMenu82.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu82.setText("Mantenimiento");

        jMenu89.setText("Usuario");
        jMenu82.add(jMenu89);

        jMenu84.setText("Cliente");
        jMenu82.add(jMenu84);

        jMenu85.setText("Articulo");
        jMenu82.add(jMenu85);

        jMenu86.setText("Provedor");
        jMenu82.add(jMenu86);

        jMenu87.setText("Tipo de articulo");
        jMenu82.add(jMenu87);

        jMenu88.setText("Marca");
        jMenu82.add(jMenu88);

        jMenu90.setText("jMenu90");
        jMenu82.add(jMenu90);

        jMenu91.setText("jMenu91");
        jMenu82.add(jMenu91);

        jMenu92.setText("jMenu92");
        jMenu82.add(jMenu92);

        jMenu93.setText("jMenu93");
        jMenu82.add(jMenu93);

        JPmenu.add(jMenu82);

        jMenu5.setText("Articulo");
        JPmenu.add(jMenu5);

        jMenu6.setText("Almacen");

        jMenu41.setText("Nota salida");
        jMenu6.add(jMenu41);

        jMenu42.setText("Nota ingreso");
        jMenu6.add(jMenu42);

        jMenu43.setText("kardex");
        jMenu6.add(jMenu43);

        jMenu44.setText("Tranferencia");
        jMenu6.add(jMenu44);

        jMenu45.setText("Nota de transferencia");
        jMenu6.add(jMenu45);

        JPmenu.add(jMenu6);

        jMenu7.setText("Compras");

        jMenu46.setText("Orden de compra");
        jMenu7.add(jMenu46);

        jMenu47.setText("Compra");
        jMenu7.add(jMenu47);

        jMenu48.setText("General letras de compra");
        jMenu7.add(jMenu48);

        jMenu49.setText("Letras de compras");
        jMenu7.add(jMenu49);

        jMenu50.setText("Nota de credito de compras");
        jMenu7.add(jMenu50);

        jMenu51.setText("Nota de debito de compras");
        jMenu7.add(jMenu51);

        jMenu52.setText("Registrar pagos de las compras");
        jMenu7.add(jMenu52);

        JPmenu.add(jMenu7);

        jMenu8.setText("Ventas");

        jMenu53.setText("Contrato");
        jMenu8.add(jMenu53);

        jMenu54.setText("Cotizacion");
        jMenu8.add(jMenu54);

        jMenu55.setText("Recibo");

        jMenu83.setText("Factura");
        jMenu55.add(jMenu83);

        jMenu8.add(jMenu55);

        jMenu56.setText("Documento de venta");
        jMenu8.add(jMenu56);

        jMenu57.setText("Guia Remición ");
        jMenu8.add(jMenu57);

        jMenu58.setText("General letras de ventas");
        jMenu8.add(jMenu58);

        jMenu59.setText("Nota de credito");
        jMenu8.add(jMenu59);

        jMenu60.setText("Nota de debito de venta");
        jMenu8.add(jMenu60);

        jMenu61.setText("Registro cobro de las ventas");
        jMenu8.add(jMenu61);

        jMenu62.setText("Estadistica de ventas");
        jMenu8.add(jMenu62);

        JPmenu.add(jMenu8);

        jMenu9.setText("Comprovantes");

        jMenu63.setText("Registro de comprovante");
        jMenu9.add(jMenu63);

        jMenu64.setText("Comprovante por pagar");
        jMenu9.add(jMenu64);

        JPmenu.add(jMenu9);

        jMenu10.setText("Gastos");

        jMenu11.setText("Gastos");
        jMenu10.add(jMenu11);

        jMenu65.setText("Ingresos");
        jMenu10.add(jMenu65);

        JPmenu.add(jMenu10);

        jMenu12.setText("Caja");

        jMenu66.setText("Caja chica Inicial");
        jMenu12.add(jMenu66);

        jMenu67.setText("Liquidacion diaria");
        jMenu12.add(jMenu67);

        jMenu68.setText("Cuadre de caja");
        jMenu12.add(jMenu68);

        JPmenu.add(jMenu12);

        jMenu13.setText("Reporte");

        jMenu14.setText("Reporte general compras");
        jMenu13.add(jMenu14);

        jMenu69.setText("Reporte general ventas");
        jMenu13.add(jMenu69);

        jMenu70.setText("Utilidades de ventas");
        jMenu13.add(jMenu70);

        JPmenu.add(jMenu13);

        jMenu15.setText("Claves");

        jMenu71.setText("Permisos");
        jMenu15.add(jMenu71);

        JPmenu.add(jMenu15);

        jMenu16.setText("Finanzas");

        jMenu72.setText("Contabilidad");
        jMenu16.add(jMenu72);

        jMenu73.setText("Impuestos");
        jMenu16.add(jMenu73);

        jMenu74.setText("Financiamiento");
        jMenu16.add(jMenu74);

        jMenu75.setText("Planación Financiera");
        jMenu16.add(jMenu75);

        jMenu76.setText("Prosupuesto");
        jMenu16.add(jMenu76);

        jMenu77.setText("Costos");
        jMenu16.add(jMenu77);

        JPmenu.add(jMenu16);

        jMenu18.setText("Utilitarios");

        jMenu78.setText("Calculadora");
        jMenu18.add(jMenu78);

        jMenu79.setText("Blonck notas");
        jMenu18.add(jMenu79);

        JPmenu.add(jMenu18);

        jMenu17.setText("Salir");

        jMenu80.setText("Salir");
        jMenu17.add(jMenu80);

        JPmenu.add(jMenu17);

        jMenu94.setText("jMenu94");
        JPmenu.add(jMenu94);

        setJMenuBar(JPmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNActionPerformed

    private void RHusuarioPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RHusuarioPrincipalActionPerformed
        
    }//GEN-LAST:event_RHusuarioPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN;
    private javax.swing.JMenuBar JPmenu;
    private javax.swing.JPanel JPprincipal;
    private javax.swing.JMenu RHadelantosPrincipal;
    private javax.swing.JMenu RHasistenciaPrinicpal;
    private javax.swing.JMenu RHextrasPrincipal;
    private javax.swing.JMenu RHjornadaPrincipal;
    private javax.swing.JMenu RHpagosPrincipal;
    private javax.swing.JMenu RHpersonalPrincipal;
    private javax.swing.JMenu RHreportesPrincipal;
    private javax.swing.JMenu RHusuarioPrincipal;
    private javax.swing.JMenu RHvacacionesPrinicipal;
    private javax.swing.JMenu RHvolverPrinicpal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu55;
    private javax.swing.JMenu jMenu56;
    private javax.swing.JMenu jMenu57;
    private javax.swing.JMenu jMenu58;
    private javax.swing.JMenu jMenu59;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu60;
    private javax.swing.JMenu jMenu61;
    private javax.swing.JMenu jMenu62;
    private javax.swing.JMenu jMenu63;
    private javax.swing.JMenu jMenu64;
    private javax.swing.JMenu jMenu65;
    private javax.swing.JMenu jMenu66;
    private javax.swing.JMenu jMenu67;
    private javax.swing.JMenu jMenu68;
    private javax.swing.JMenu jMenu69;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu70;
    private javax.swing.JMenu jMenu71;
    private javax.swing.JMenu jMenu72;
    private javax.swing.JMenu jMenu73;
    private javax.swing.JMenu jMenu74;
    private javax.swing.JMenu jMenu75;
    private javax.swing.JMenu jMenu76;
    private javax.swing.JMenu jMenu77;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu81;
    private javax.swing.JMenu jMenu82;
    private javax.swing.JMenu jMenu83;
    private javax.swing.JMenu jMenu84;
    private javax.swing.JMenu jMenu85;
    private javax.swing.JMenu jMenu86;
    private javax.swing.JMenu jMenu87;
    private javax.swing.JMenu jMenu88;
    private javax.swing.JMenu jMenu89;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenu90;
    private javax.swing.JMenu jMenu91;
    private javax.swing.JMenu jMenu92;
    private javax.swing.JMenu jMenu93;
    private javax.swing.JMenu jMenu94;
    // End of variables declaration//GEN-END:variables
}
